<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-7C7M603" name="Fuctional testing" tests="6" failures="2" timestamp="14 Jul 2019 04:45:58 GMT" time="88.214" errors="0">
  <testcase name="@BeforeClass isSkip" time="0.0" classname="com.companyName.projectName.module.testCases.TC002_Create_An_Account">
    <skipped/>
  </testcase> <!-- @BeforeClass isSkip -->
  <testcase name="@BeforeClass isSkip" time="0.0" classname="com.companyName.projectName.module.testCases.TC004_Create_An_Account">
    <skipped/>
  </testcase> <!-- @BeforeClass isSkip -->
  <testcase name="@BeforeClass isSkip" time="0.0" classname="com.companyName.projectName.module.testCases.TC005_Create_An_Account">
    <skipped/>
  </testcase> <!-- @BeforeClass isSkip -->
  <testcase name="TC001_Create_an_Account" time="27.349" classname="com.companyName.projectName.module.testCases.TC001_Create_An_Account"/>
  <testcase name="TC002_Create_an_Account" time="0.001" classname="com.companyName.projectName.module.testCases.TC002_Create_An_Account">
    <skipped/>
  </testcase> <!-- TC002_Create_an_Account -->
  <testcase name="TC003_Create_an_Account" time="28.852" classname="com.companyName.projectName.module.testCases.TC003_Create_An_Account">
    <failure type="java.lang.AssertionError" message="Please enter all required fields">
      <![CDATA[java.lang.AssertionError: Please enter all required fields
	at org.testng.Assert.fail(Assert.java:94)
	at com.companyName.projectName.module.pages.LandingPage.registerUser(LandingPage.java:105)
	at com.companyName.projectName.module.testCases.TC003_Create_An_Account.TC003_Create_an_Account(TC003_Create_An_Account.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- TC003_Create_an_Account -->
  <testcase name="TC003_Create_an_Account" time="26.652" classname="com.companyName.projectName.module.testCases.TC003_Create_An_Account">
    <failure type="java.lang.AssertionError" message="Please enter all required fields">
      <![CDATA[java.lang.AssertionError: Please enter all required fields
	at org.testng.Assert.fail(Assert.java:94)
	at com.companyName.projectName.module.pages.LandingPage.registerUser(LandingPage.java:105)
	at com.companyName.projectName.module.testCases.TC003_Create_An_Account.TC003_Create_an_Account(TC003_Create_An_Account.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:995)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1175)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- TC003_Create_an_Account -->
  <testcase name="TC004_Create_an_Account" time="0.001" classname="com.companyName.projectName.module.testCases.TC004_Create_An_Account">
    <skipped/>
  </testcase> <!-- TC004_Create_an_Account -->
  <testcase name="TC005_Create_an_Account" time="0.001" classname="com.companyName.projectName.module.testCases.TC005_Create_An_Account">
    <skipped/>
  </testcase> <!-- TC005_Create_an_Account -->
</testsuite> <!-- Fuctional testing -->
